### ISSUE TITLE
Stylize Navbar

### ISSUE THREAD

**Issue by LegendArtur** [yasminehilout/Big-Eaters-soen341project2023#17]
It has to be centered with a different color than the background.

Inspirations:

![image](https://user-images.githubusercontent.com/29106800/219282152-1d04e998-6bcc-4497-9c0e-3c626aa91adc.png)

![image](https://user-images.githubusercontent.com/29106800/219282183-86b90280-34e4-4bac-ac84-f6b9ecf87cda.png)

**Comment by lo-vil** [comment]
Since Sign-in behaviour was changed, just stylize the navbar which consists of the profile icon and sign in / sign out forms / buttons.
