### ISSUE TITLE
Stylize the Job Postings page.

### ISSUE THREAD

**Issue by LegendArtur** [yasminehilout/Big-Eaters-soen341project2023#18]
This design has been worked on during our UI design session.

Could use Material UI to rebuild some Components:

example  "Apply" button or "Sign-In" button can be taken from
https://mui.com/material-ui/react-button/

**Comment by lo-vil** [comment]
<img width="545" alt="Screenshot 2023-02-24 at 3 11 23 PM" src="https://user-images.githubusercontent.com/94203138/221281475-edabc9a7-38ea-44d7-9bf6-229069d82e07.png">

Potential Design for job postings page
