### ISSUE TITLE
User Story 1: Student profile creation

### ISSUE THREAD

**Issue by justncheng** [yasminehilout/Big-Eaters-soen341project2023#4]
The career services platform shall allow student users to select that they are a student and create a profile and login in a well-designed interface within 5 minutes.

**Comment by ctmoon20** [comment]
The candidate should be able to filter job postings based on the preferred skills that are asked, as well as upload their resume and edit their candidate profile.

**Comment by LegendArtur** [comment]
As a student I would like to be able to browse available job postings easily
because I want to quickly find job posting that match my skills
